apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: novopattern-com-tls
spec:
  secretName: novopattern-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: novopattern.com
  dnsNames:
    - novopattern.com
    - www.novopattern.com
