apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: novopattern-com-tls
spec:
  secretName: novopattern-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: novopattern.com
  dnsNames:
    - novopattern.com
    - www.novopattern.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - novopattern.com
          - www.novopattern.com